# Generated by Django 5.1.2 on 2025-09-15 22:48

import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='home', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='en', max_length=20)),
                ('english_name', models.CharField(default='English', max_length=200)),
                ('native_name', models.CharField(default='English', max_length=200)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(default='', max_length=500)),
                ('code', models.CharField(default='item', max_length=100)),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/category_image/defaults/nav-cover.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1000, 100], upload_to='category_image/')),
                ('display', models.BooleanField(default=False)),
                ('display_cover', models.BooleanField(default=True)),
                ('display_image', models.BooleanField(default=False)),
                ('display_text', models.BooleanField(default=True)),
                ('icon', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/category_image/defaults/nav-icon.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[30, 30], upload_to='category_image/')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/category_image/defaults/nav-image.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[60, 30], upload_to='category_image/')),
                ('img_type', models.CharField(default='icon', max_length=500)),
                ('index', models.IntegerField(default=1)),
                ('local', models.CharField(default='menu', max_length=200)),
                ('local_type', models.CharField(default='list', max_length=200)),
                ('parent', models.CharField(default='', max_length=200)),
                ('posts_by_index', models.BooleanField(default=False)),
                ('warning', models.CharField(default='', max_length=200)),
                ('warning_id_exists', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NavItemString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='item', max_length=100)),
                ('lang', models.CharField(default='en', max_length=50)),
                ('subtitle', models.CharField(default='', max_length=200)),
                ('summary', models.CharField(default='', max_length=2000)),
                ('text', models.CharField(default='Item', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/brand_image/defaults/brand.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[100, 30], upload_to='brand_image/')),
                ('default_lang', models.CharField(default='en', max_length=20)),
                ('display_brand', models.BooleanField(default=False)),
                ('display_logo', models.BooleanField(default=True)),
                ('display_name', models.BooleanField(default=False)),
                ('favicon', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/brand_image/defaults/favicon.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[16, 16], upload_to='brand_image/')),
                ('lang', models.CharField(default='en', max_length=20)),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/brand_image/defaults/logo.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[30, 30], upload_to='brand_image/')),
                ('name', models.CharField(default='Nebula', max_length=200)),
                ('posts_for_page', models.IntegerField(default=5)),
                ('style', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PageStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=1)),
                ('nav_top_bg', models.CharField(default='#000000', max_length=10)),
                ('nav_top_fg', models.CharField(default='#CCCCCC', max_length=10)),
                ('nav_top_fg_hover', models.CharField(default='#FFFFFF', max_length=10)),
                ('nav_bottom_fg', models.CharField(default='#CCCCCC', max_length=10)),
                ('nav_items_bg', models.CharField(default='#000000', max_length=10)),
                ('nav_bottom_bg', models.CharField(default='#000000', max_length=10)),
                ('nav_items_fg', models.CharField(default='#CCCCCC', max_length=10)),
                ('nav_items_fg_hover', models.CharField(default='#FFFFFF', max_length=10)),
                ('body_fg', models.CharField(default='#555555', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(default='home,home-highlight', max_length=200)),
                ('code', models.CharField(default='TR0', max_length=20)),
                ('content', models.TextField(default='')),
                ('content_file', models.FileField(default='', upload_to='content_doc/')),
                ('cover_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='/cover_image/defaults/cover.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1000, 400], upload_to='cover_image/')),
                ('cover_image_thumb', models.CharField(default='/media/cover_image/defaults/cover-thumb.png', max_length=300)),
                ('cover_image_credits', models.CharField(default='Bubble Nebula, by Nasa', max_length=200)),
                ('cover_image_credits_link', models.CharField(default='https://www.nasa.gov/nasa-brand-center/images-and-media/', max_length=200)),
                ('display', models.BooleanField(default=False)),
                ('index', models.IntegerField(default=1)),
                ('lang', models.CharField(default='en', max_length=50)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='New', max_length=90)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.CharField(default='new', max_length=200)),
                ('warning', models.CharField(default='', max_length=500)),
                ('warning_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webpage.post')),
            ],
            bases=('webpage.post',),
        ),
    ]
