# Generated by Django 5.1.2 on 2025-09-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagestyle',
            name='nav_bottom_fg',
        ),
        migrations.RemoveField(
            model_name='pagestyle',
            name='nav_items_bg',
        ),
        migrations.AlterField(
            model_name='pagesetting',
            name='display_brand',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pagesetting',
            name='display_logo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='nav_bottom_bg',
            field=models.CharField(default='#222222', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='nav_top_bg',
            field=models.CharField(default='#222222', max_length=10),
        ),
    ]
