# Generated by Django 5.1.2 on 2024-10-15 04:21

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/category_image/nav-image.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 150], upload_to='category_image/'),
        ),
        migrations.AddField(
            model_name='navitem',
            name='local',
            field=models.CharField(default='menu', max_length=200),
        ),
    ]
