# Generated by Django 5.1.2 on 2025-09-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icons',
            name='clos_icon',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icons',
            name='close_file',
            field=models.FileField(default='icons/default/clos.svg', upload_to='icons/'),
        ),
    ]
