# Generated by Django 5.1.2 on 2025-09-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_icons_clos_icon_icons_close_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icons',
            name='close_file',
            field=models.FileField(default='icons/default/close.svg', upload_to='icons/'),
        ),
    ]
