# Generated by Django 5.1.2 on 2024-10-15 04:51

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_navitem_cover_navitem_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/category_image/nav-cover.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 150], upload_to='category_image/'),
        ),
    ]
