# Generated by Django 5.1.2 on 2025-09-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_alter_icons_close_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Icons',
            new_name='Icon',
        ),
    ]
