# Generated by Django 5.1.2 on 2024-10-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_alter_navitem_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='parent',
            field=models.CharField(default='', max_length=200),
        ),
    ]
