# Generated by Django 5.1.2 on 2024-10-15 20:02

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_navitem_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='cover_thumb',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/category_image/defaults/nav-cover-thumb.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 150], upload_to='category_image/'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/category_image/defaults/nav-cover.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1000, 400], upload_to='category_image/'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/category_image/defaults/nav-icon.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[30, 30], upload_to='category_image/'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/category_image/defaults/nav-image.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[60, 30], upload_to='category_image/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='/cover_image/defaults/cover.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1000, 400], upload_to='cover_image/'),
        ),
    ]
