# Generated by Django 5.1.2 on 2025-09-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_rename_icons_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='trash_file',
            field=models.FileField(default='icons/default/trash.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='trash_icon',
            field=models.TextField(default=''),
        ),
    ]
