# Generated by Django 5.1.2 on 2024-10-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_navitem_cover_thumb_alter_navitem_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='navitem',
            name='local_type',
            field=models.CharField(default='list', max_length=200),
        ),
    ]
