# Generated by Django 5.1.2 on 2025-09-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_icon_trash_file_icon_trash_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icon',
            old_name='clos_icon',
            new_name='close_icon',
        ),
    ]
