# Generated by Django 5.1.2 on 2024-10-16 04:13

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_navitem_content_navitem_local_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/category_image/defaults/nav-cover.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1000, 200], upload_to='category_image/'),
        ),
    ]
