# Generated by Django 5.1.2 on 2025-09-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_rename_clos_icon_icon_close_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='light_file',
            field=models.FileField(default='icons/default/light.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='light_icon',
            field=models.TextField(default=''),
        ),
    ]
