# Generated by Django 5.1.2 on 2024-10-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_alter_navitem_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='display_cover',
            field=models.BooleanField(default=False),
        ),
    ]
