# Generated by Django 5.1.2 on 2025-09-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_icon_light_file_icon_light_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='plus_ref_file',
            field=models.FileField(default='icons/default/plus_ref.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='plus_ref_icon',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='quest_ref_file',
            field=models.FileField(default='icons/default/quest_ref.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='quest_ref_icon',
            field=models.TextField(default=''),
        ),
    ]
