# Generated by Django 5.1.2 on 2025-09-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_icon_plus_ref_file_icon_plus_ref_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='arrow_restore_45deg_file',
            field=models.FileField(default='icons/default/arrow-restore-45deg.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='arrow_restore_45deg_icon',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='arrow_restore_file',
            field=models.FileField(default='icons/default/arrow-restore.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='arrow_restore_icon',
            field=models.TextField(default=''),
        ),
    ]
