# Generated by Django 5.1.2 on 2024-10-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0009_alter_navitem_cover_alter_navitem_cover_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='display_cover',
            field=models.BooleanField(default=True),
        ),
    ]
