# Generated by Django 5.1.2 on 2025-09-23 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0009_icon_arrow_restore_45deg_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icon',
            old_name='arrow_restore_45deg_file',
            new_name='arrow_restore_45_file',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='arrow_restore_45deg_icon',
            new_name='arrow_restore_45_icon',
        ),
    ]
