# Generated by Django 5.1.2 on 2024-10-16 19:12

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_alter_navitem_display_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/category_image/defaults/nav-cover.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1000, 100], upload_to='category_image/'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='cover_thumb',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/category_image/defaults/nav-cover-thumb.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 100], upload_to='category_image/'),
        ),
    ]
