# Generated by Django 5.1.2 on 2025-09-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_rename_arrow_restore_45deg_file_icon_arrow_restore_45_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='search_file',
            field=models.FileField(default='icons/default/search.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='search_icon',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='settings_file',
            field=models.FileField(default='icons/default/settings.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='settings_icon',
            field=models.TextField(default=''),
        ),
    ]
