# Generated by Django 5.1.2 on 2024-10-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0011_alter_navitem_cover_alter_navitem_cover_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='content_file',
            field=models.FileField(default='', upload_to='category_content_doc/'),
        ),
    ]
