# Generated by Django 5.1.2 on 2025-09-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0011_icon_search_file_icon_search_icon_icon_settings_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='admin_file',
            field=models.FileField(default='icons/default/admin.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='admin_icon',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='image_file',
            field=models.FileField(default='icons/default/image.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='image_icon',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='post_file',
            field=models.FileField(default='icons/default/post.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='post_icon',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='style_file',
            field=models.FileField(default='icons/default/style.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='style_icon',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='translate_file',
            field=models.FileField(default='icons/default/translate.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='translate_icon',
            field=models.TextField(default=''),
        ),
    ]
