# Generated by Django 5.1.2 on 2024-10-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_navitem_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='cover_thumb',
            field=models.CharField(default='/category_image/defaults/nav-cover-thumb.png', max_length=300),
        ),
    ]
