# Generated by Django 5.1.2 on 2025-09-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_icon_admin_file_icon_admin_icon_icon_image_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icon',
            old_name='admin_icon',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='arrow_restore_45_icon',
            new_name='arrow_restore',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='arrow_restore_icon',
            new_name='arrow_restore_45',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='book_icon',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='close_icon',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='image_icon',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='light_icon',
            new_name='light',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='plus_icon',
            new_name='plus',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='plus_ref_icon',
            new_name='plus_ref',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='post_icon',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='quest_ref_icon',
            new_name='quest_ref',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='search_icon',
            new_name='search',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='settings_icon',
            new_name='settings',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='style_icon',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='translate_icon',
            new_name='translate',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='trash_icon',
            new_name='trash',
        ),
        migrations.AlterField(
            model_name='icon',
            name='check_file',
            field=models.FileField(default='icons/default/ok.svg', upload_to='icons/'),
        ),
    ]
