# Generated by Django 5.1.2 on 2025-09-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0013_rename_admin_icon_icon_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icon',
            old_name='check_icon',
            new_name='ok',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='check_file',
            new_name='ok_file',
        ),
    ]
