# Generated by Django 5.1.2 on 2025-09-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0014_rename_check_icon_icon_ok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='warning',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='warning_file',
            field=models.FileField(default='icons/default/warning.svg', upload_to='icons/'),
        ),
    ]
