# Generated by Django 5.1.2 on 2025-09-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0015_icon_warning_icon_warning_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='link_file',
            field=models.FileField(default='icons/default/link.svg', upload_to='icons/'),
        ),
    ]
