# Generated by Django 5.1.2 on 2024-10-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0015_remove_navitem_cover_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image_thumb',
            field=models.CharField(default='/media/cover_image/defaults/cover-thumb.png', max_length=300),
        ),
    ]
