# Generated by Django 5.1.2 on 2024-10-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0016_post_cover_image_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_top_bg', models.CharField(default='#000000FF', max_length=10)),
                ('nav_top_fg', models.CharField(default='#CCCCCCFF', max_length=10)),
                ('nav_bottom_bg', models.CharField(default='#000000FF', max_length=10)),
                ('nav_bottom_fg', models.CharField(default='#CCCCCCFF', max_length=10)),
                ('nav_items_bg', models.CharField(default='#000000FF', max_length=10)),
                ('nav_items_fg', models.CharField(default='#CCCCCCFF', max_length=10)),
                ('nav_items_fg_hover', models.CharField(default='#FFFFFFFF', max_length=10)),
                ('body_fg', models.CharField(default='#555555FF', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='pagesetting',
            name='style',
            field=models.IntegerField(default=1),
        ),
    ]
