# Generated by Django 5.1.2 on 2025-09-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0016_icon_link_icon_link_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='clock',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='clock_file',
            field=models.FileField(default='icons/default/clock.svg', upload_to='icons/'),
        ),
    ]
