# Generated by Django 5.1.2 on 2024-10-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0017_pagestyle_pagesetting_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagestyle',
            name='code',
            field=models.IntegerField(default=1),
        ),
    ]
