# Generated by Django 5.1.2 on 2025-09-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0017_icon_clock_icon_clock_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='hidden',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='hidden_file',
            field=models.FileField(default='icons/default/hidden.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='visible',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='visible_file',
            field=models.FileField(default='icons/default/visible.svg', upload_to='icons/'),
        ),
    ]
