# Generated by Django 5.1.2 on 2024-10-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0018_pagestyle_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagestyle',
            name='nav_top_fg_hover',
            field=models.CharField(default='#FFFFFFFF', max_length=10),
        ),
    ]
