# Generated by Django 5.1.2 on 2025-09-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0018_icon_hidden_icon_hidden_file_icon_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='card',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='card_file',
            field=models.FileField(default='icons/default/card.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='category_file',
            field=models.FileField(default='icons/default/category.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='content_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='content_text_file',
            field=models.FileField(default='icons/default/content_text.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='tag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='tag_file',
            field=models.FileField(default='icons/default/tag.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='title_file',
            field=models.FileField(default='icons/default/title.svg', upload_to='icons/'),
        ),
    ]
