# Generated by Django 5.1.2 on 2024-10-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0019_pagestyle_nav_top_fg_hover'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitemstring',
            name='subtitle',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='navitemstring',
            name='summary',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
