# Generated by Django 5.1.2 on 2025-09-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0019_icon_card_icon_card_file_icon_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='arrow_left',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='arrow_left_file',
            field=models.FileField(default='icons/default/arrow-left.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='arrow_right',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='arrow_right_file',
            field=models.FileField(default='icons/default/arrow-right.svg', upload_to='icons/'),
        ),
    ]
