# Generated by Django 5.1.2 on 2024-10-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0020_navitemstring_subtitle_navitemstring_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
