# Generated by Django 5.1.2 on 2025-09-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0020_icon_arrow_left_icon_arrow_left_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='edit',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='edit_file',
            field=models.FileField(default='icons/default/edit.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='edit_warning',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='edit_warning_file',
            field=models.FileField(default='icons/default/edit-warning.svg', upload_to='icons/'),
        ),
    ]
