# Generated by Django 5.1.2 on 2025-02-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0021_navitem_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navitem',
            name='content',
        ),
        migrations.RemoveField(
            model_name='navitem',
            name='content_file',
        ),
    ]
