# Generated by Django 5.1.2 on 2025-09-24 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0021_icon_edit_icon_edit_file_icon_edit_warning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='edit_warning',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='edit_warning_file',
        ),
    ]
