# Generated by Django 5.1.2 on 2025-02-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0022_remove_navitem_content_remove_navitem_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
