# Generated by Django 5.1.2 on 2025-09-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0022_remove_icon_edit_warning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='grid',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='grid_file',
            field=models.FileField(default='icons/default/grid.svg', upload_to='icons/'),
        ),
    ]
