# Generated by Django 5.1.2 on 2025-09-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0023_icon_grid_icon_grid_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='font',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='font_file',
            field=models.FileField(default='icons/default/font.svg', upload_to='icons/'),
        ),
    ]
