# Generated by Django 5.1.2 on 2025-09-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0023_alter_navitem_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
