# Generated by Django 5.1.2 on 2025-09-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0024_icon_font_icon_font_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='font_ref',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='font_ref_file',
            field=models.FileField(default='icons/default/font_ref.svg', upload_to='icons/'),
        ),
    ]
