# Generated by Django 5.1.2 on 2025-09-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0024_post_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='posts_by_index',
            field=models.BooleanField(default=False),
        ),
    ]
