# Generated by Django 5.1.2 on 2025-10-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0025_icon_font_ref_icon_font_ref_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icon',
            old_name='font',
            new_name='src',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='font_ref',
            new_name='src_ref',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='font_file',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='font_ref_file',
        ),
        migrations.AddField(
            model_name='icon',
            name='src_file',
            field=models.FileField(default='icons/default/src.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='src_ref_file',
            field=models.FileField(default='icons/default/src_ref.svg', upload_to='icons/'),
        ),
    ]
