# Generated by Django 5.1.2 on 2025-09-12 03:27

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0025_navitem_posts_by_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesetting',
            name='brand',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/category_image/defaults/brand.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[30, 100], upload_to='category_image/'),
        ),
        migrations.AddField(
            model_name='pagesetting',
            name='favicon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/category_image/defaults/favicon.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[16, 16], upload_to='category_image/'),
        ),
        migrations.AddField(
            model_name='pagesetting',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/category_image/defaults/logo.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[30, 30], upload_to='category_image/'),
        ),
    ]
