# Generated by Django 5.1.2 on 2025-10-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0026_rename_font_icon_src_rename_font_ref_icon_src_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='src_ref',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='src_ref_file',
        ),
    ]
