# Generated by Django 5.1.2 on 2025-09-12 03:29

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0026_pagesetting_brand_pagesetting_favicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesetting',
            name='brand',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/category_image/defaults/brand.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[100, 30], upload_to='category_image/'),
        ),
    ]
