# Generated by Django 5.1.2 on 2025-09-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0027_alter_pagesetting_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesetting',
            name='display_brand',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagesetting',
            name='display_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagesetting',
            name='display_name',
            field=models.BooleanField(default=True),
        ),
    ]
