# Generated by Django 5.1.2 on 2025-10-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0027_remove_icon_src_ref_remove_icon_src_ref_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagestyle',
            name='body_bg',
            field=models.CharField(default='#DEDECD', max_length=10),
        ),
    ]
