# Generated by Django 5.1.2 on 2025-10-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0028_pagestyle_body_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagestyle',
            name='body_link',
            field=models.CharField(default='#1D5AA3', max_length=10),
        ),
        migrations.AddField(
            model_name='pagestyle',
            name='body_link_hover',
            field=models.CharField(default='#194C8B', max_length=10),
        ),
        migrations.AddField(
            model_name='pagestyle',
            name='body_title',
            field=models.CharField(default='#426EC1', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='body_fg',
            field=models.CharField(default='#434343', max_length=10),
        ),
    ]
