# Generated by Django 5.1.2 on 2025-09-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0028_pagesetting_display_brand_pagesetting_display_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesetting',
            name='display_brand',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pagesetting',
            name='display_name',
            field=models.BooleanField(default=False),
        ),
    ]
