# Generated by Django 5.1.2 on 2025-09-12 16:02

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0029_alter_pagesetting_display_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesetting',
            name='brand',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/brand_image/defaults/brand.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[100, 30], upload_to='brand_image/'),
        ),
        migrations.AlterField(
            model_name='pagesetting',
            name='favicon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/brand_image/defaults/favicon.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[16, 16], upload_to='brand_image/'),
        ),
        migrations.AlterField(
            model_name='pagesetting',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/brand_image/defaults/logo.svg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[30, 30], upload_to='brand_image/'),
        ),
    ]
