# Generated by Django 5.1.2 on 2025-10-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0029_pagestyle_body_link_pagestyle_body_link_hover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagestyle',
            name='body_bg_alt',
            field=models.CharField(default='#EEEEEE', max_length=10),
        ),
    ]
