# Generated by Django 5.1.2 on 2025-10-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0030_pagestyle_body_bg_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagestyle',
            name='body_bg_alt_dark',
            field=models.CharField(default='#333333', max_length=10),
        ),
        migrations.AddField(
            model_name='pagestyle',
            name='body_bg_dark',
            field=models.CharField(default='#222222', max_length=10),
        ),
        migrations.AddField(
            model_name='pagestyle',
            name='body_fg_dark',
            field=models.CharField(default='#EEEEEE', max_length=10),
        ),
        migrations.AddField(
            model_name='pagestyle',
            name='body_link_dark',
            field=models.CharField(default='#1D5AA3', max_length=10),
        ),
        migrations.AddField(
            model_name='pagestyle',
            name='body_link_hover_dark',
            field=models.CharField(default='#194C8B', max_length=10),
        ),
        migrations.AddField(
            model_name='pagestyle',
            name='body_title_dark',
            field=models.CharField(default='#426EC1', max_length=10),
        ),
        migrations.AddField(
            model_name='pagestyle',
            name='is_dark',
            field=models.BooleanField(default=False),
        ),
    ]
