# Generated by Django 5.1.2 on 2025-09-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0030_alter_pagesetting_brand_alter_pagesetting_favicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesetting',
            name='lang',
        ),
    ]
