# Generated by Django 5.1.2 on 2025-09-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0031_remove_pagesetting_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesetting',
            name='default_lang',
            field=models.CharField(default='en', max_length=20),
        ),
    ]
