# Generated by Django 5.1.2 on 2025-10-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0031_pagestyle_body_bg_alt_dark_pagestyle_body_bg_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='circle_half',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='circle_half_file',
            field=models.FileField(default='icons/default/circle-half.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='moon',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='moon_file',
            field=models.FileField(default='icons/default/moon.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='sun',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='sun_file',
            field=models.FileField(default='icons/default/sun.svg', upload_to='icons/'),
        ),
    ]
