# Generated by Django 5.1.2 on 2025-10-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0032_icon_circle_half_icon_circle_half_file_icon_moon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagestyle',
            name='body_bg_alt',
            field=models.CharField(default='#EBEBD9', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='body_bg_dark',
            field=models.CharField(default='#272727', max_length=10),
        ),
    ]
