# Generated by Django 5.1.2 on 2025-09-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0032_pagesetting_default_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesetting',
            name='posts_for_page',
            field=models.IntegerField(default=5),
        ),
    ]
