# Generated by Django 5.1.2 on 2025-10-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0033_alter_pagestyle_body_bg_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagestyle',
            name='body_fg_dark',
            field=models.CharField(default='#DDDDDD', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='body_link_dark',
            field=models.CharField(default='#3B65A3', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='body_link_hover_dark',
            field=models.CharField(default='#2D4E7C', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='body_title',
            field=models.CharField(default='#766646', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='body_title_dark',
            field=models.CharField(default='#3C5A86', max_length=10),
        ),
    ]
