# Generated by Django 5.1.2 on 2025-09-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0033_pagesetting_posts_for_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagestyle',
            name='body_fg',
            field=models.CharField(default='#555555', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='nav_bottom_bg',
            field=models.CharField(default='#000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='nav_bottom_fg',
            field=models.CharField(default='#CCCCCC', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='nav_items_bg',
            field=models.CharField(default='#000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='nav_items_fg',
            field=models.CharField(default='#CCCCCC', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='nav_items_fg_hover',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='nav_top_bg',
            field=models.CharField(default='#000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='nav_top_fg',
            field=models.CharField(default='#CCCCCC', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='nav_top_fg_hover',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
    ]
