# Generated by Django 5.1.2 on 2025-10-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0034_alter_pagestyle_body_fg_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagestyle',
            name='body_selection_bg',
            field=models.CharField(default='#CEB24E', max_length=10),
        ),
        migrations.AddField(
            model_name='pagestyle',
            name='body_selection_bg_dark',
            field=models.CharField(default='#AC9541', max_length=10),
        ),
        migrations.AddField(
            model_name='pagestyle',
            name='body_selection_fg',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
        migrations.AddField(
            model_name='pagestyle',
            name='body_selection_fg_dark',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
    ]
