# Generated by Django 5.1.2 on 2025-10-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0035_pagestyle_body_selection_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagestyle',
            name='body_highlight_bg',
            field=models.CharField(default='#FFF23822', max_length=10),
        ),
        migrations.AddField(
            model_name='pagestyle',
            name='body_highlight_bg_dark',
            field=models.CharField(default='#FFF23822', max_length=10),
        ),
    ]
