# Generated by Django 5.1.2 on 2025-10-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0036_pagestyle_body_highlight_bg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagestyle',
            name='body_highlight_bg',
            field=models.CharField(default='#FFF23877', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='body_highlight_bg_dark',
            field=models.CharField(default='#FFF23877', max_length=10),
        ),
    ]
