# Generated by Django 5.1.2 on 2025-10-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0037_alter_pagestyle_body_highlight_bg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagestyle',
            name='body_title',
            field=models.CharField(default='#887142', max_length=10),
        ),
    ]
