# Generated by Django 5.1.2 on 2025-10-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0038_alter_pagestyle_body_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagestyle',
            name='body_selection_bg',
            field=models.CharField(default='#BBBBBB', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='body_selection_bg_dark',
            field=models.CharField(default='#3D3D3D', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='body_selection_fg',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
