# Generated by Django 5.1.2 on 2026-06-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0039_alter_pagestyle_body_selection_bg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagestyle',
            name='body_highlight_bg_dark',
            field=models.CharField(default='#766646', max_length=10),
        ),
    ]
