# Generated by Django 5.1.2 on 2026-06-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0040_alter_pagestyle_body_highlight_bg_dark'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='cita_end',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='cita_end_file',
            field=models.FileField(default='icons/default/cita_end.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='cita_start',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icon',
            name='cita_start_file',
            field=models.FileField(default='icons/default/cita_start.svg', upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='body_fg_dark',
            field=models.CharField(default='#B1B1B1', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='body_highlight_bg',
            field=models.CharField(default='#887142', max_length=10),
        ),
    ]
