# Generated by Django 5.1.2 on 2026-06-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0041_icon_cita_end_icon_cita_end_file_icon_cita_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagestyle',
            name='body_highlight_bg',
            field=models.CharField(default='#D9BA7C', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='body_highlight_bg_dark',
            field=models.CharField(default='#4A453A', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='nav_items_fg_hover',
            field=models.CharField(default='#A78E5C', max_length=10),
        ),
    ]
