# Generated by Django 5.1.2 on 2026-06-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0042_alter_pagestyle_body_highlight_bg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='TR0', max_length=20)),
                ('index', models.IntegerField(default=1)),
            ],
        ),
    ]
