# Generated by Django 5.1.2 on 2026-06-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0043_homehighlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='homehighlight',
            name='lang',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
