# Generated by Django 5.1.2 on 2026-06-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0044_homehighlight_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icon',
            old_name='cita_end',
            new_name='quote_end',
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='cita_start',
            new_name='quote_start',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='cita_end_file',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='cita_start_file',
        ),
        migrations.AddField(
            model_name='icon',
            name='quote_end_file',
            field=models.FileField(default='icons/default/quote_end.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='icon',
            name='quote_start_file',
            field=models.FileField(default='icons/default/quote_start.svg', upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='nav_bottom_bg',
            field=models.CharField(default='#000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagestyle',
            name='nav_top_bg',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
